// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
/* eslint-disable @typescript-eslint/no-empty-object-type */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your tables here
    }
    Views: {
      // Add your views here
    }
    Functions: {
      // Add your functions here
    }
    Enums: {
      // Add your enums here
    }
    CompositeTypes: {
      // Add your composite types here
    }
  }
}

// Project reference: 8ea94db5-9aa6-444c-9c67-46178d40bb74
// Last updated: 2026-04-14T08:27:56.899305
